name: androidsdk 
version: '1.2.0.0' 
summary: The package contains android sdkmanager. 
description: |
  This is snap version of console sdk manager for Android. For more information about sdkmanager see official google documentation git@github.com:EndrII/sdkmanager-android.git. 

grade: stable 
confinement: strict 
base: core22
architectures:
  - build-on: amd64
  
parts:
  androidsdk:
    # See 'snapcraft plugins'
    plugin: dump
    source: https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
    stage-packages:
      - libfreetype6
      - libpng16-16
      - openjdk-11-jdk
      - openjdk-11-jre
      - openjdk-11-jre-headless
    build-packages:
      - ca-certificates
      - ca-certificates-java
      - openjdk-11-jre-headless
    override-stage: |
      snapcraftctl stage
      chmod 777 -R "$SNAPCRAFT_STAGE/cmdline-tools"
    override-prime: |
           snapcraftctl prime
           rm -vf usr/lib/jvm/java-11-openjdk-*/lib/security/blacklisted.certs
    after:
      - androidsdk-wraper


  androidsdk-wraper:
    # See 'snapcraft plugins'
    plugin: dump
    source: scripts

apps:
  androidsdk:
    command: start.sh
    plugs:
      - home
      - removable-media
      - network
      
    environment:
      PATH: '$SNAP:$SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH'
      LD_LIBRARY_PATH: '$SNAP_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib:$SNAP/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib:$SNAP/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu'
  
    
